/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.HDNhapDAO;
import model.dao.NhaPPDAO;
import model.entity.HDNhap;
import model.entity.NhaPP;

/**
 *
 * @author hoang minh duong
 */
public class QLHoaDonNhap extends javax.swing.JPanel {

    /**
     * Creates new form QLHoaDonNhap
     */
    private NhaPPDAO nhaPPDao;
    private DefaultComboBoxModel cbmMaNPP;
    private DefaultComboBoxModel cbmTenNPP;
    private DefaultTableModel dtm;
    private HDNhapDAO hdNhapDao;
    private SimpleDateFormat format;
    private List<NhaPP> dsNPP;
    public QLHoaDonNhap() {
        nhaPPDao = new NhaPPDAO();
        cbmMaNPP = new DefaultComboBoxModel();
        cbmTenNPP = new DefaultComboBoxModel();
        dtm = new DefaultTableModel();
        hdNhapDao = new HDNhapDAO();
        format = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        tbHDN.setModel(dtm);
        dtm.addColumn("Mã HDN");
        dtm.addColumn("Ngày nhập");
        dtm.addColumn("Mã NPP");
        cbMaNPP.setModel(cbmMaNPP);
        cbTenNPP.setModel(cbmTenNPP);
        hienThiDS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbMaNPP = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHDN = new javax.swing.JTable();
        cbTenNPP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Mã NPP:");
        jLabel1.setToolTipText("");

        cbMaNPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMaNPP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaNPPItemStateChanged(evt);
            }
        });
        cbMaNPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaNPPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("HÓA ĐƠN NHẬP");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");

        tbHDN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HDN", "Ngày Nhập", " Mã NPP"
            }
        ));
        jScrollPane1.setViewportView(tbHDN);

        cbTenNPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTenNPP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTenNPPItemStateChanged(evt);
            }
        });
        cbTenNPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTenNPPActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên NPP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbTenNPP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(cbMaNPP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbMaNPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbTenNPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbMaNPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaNPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNPPActionPerformed

    private void cbTenNPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTenNPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTenNPPActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int ma = (int) cbMaNPP.getSelectedItem();
        HDNhap hd = new HDNhap(ma);
        HDNhap ok = hdNhapDao.themHDN(hd);
        if(ok!=null){
            JOptionPane.showMessageDialog(null, "Them thanh cong");
            hienThiDS();
        }else{
            JOptionPane.showMessageDialog(null, "Them that bai");
            return;
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbMaNPPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaNPPItemStateChanged
        int vt = cbMaNPP.getSelectedIndex();
        String ten = (String) cbmTenNPP.getElementAt(vt);
        cbmTenNPP.setSelectedItem(ten);
    }//GEN-LAST:event_cbMaNPPItemStateChanged

    private void cbTenNPPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTenNPPItemStateChanged
        int vt = cbTenNPP.getSelectedIndex();
        Integer ma = (Integer) cbmMaNPP.getElementAt(vt);
        cbmMaNPP.setSelectedItem(ma);
    }//GEN-LAST:event_cbTenNPPItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbMaNPP;
    private javax.swing.JComboBox<String> cbTenNPP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHDN;
    // End of variables declaration//GEN-END:variables

    private void hienThiDS() {
        List<HDNhap> listHD = hdNhapDao.getAll();
        if(listHD!=null){
            dtm.setRowCount(0);
            for (HDNhap hd : listHD) {
                dtm.addRow(new String[]{hd.getMaHDN()+"",format.format(hd.getNgayNhap()),hd.getMaNPP()+""});
            }
        }
        List<NhaPP> listNPP = nhaPPDao.getAll();
        if(listNPP!=null){
            cbmMaNPP.removeAllElements();
            for (NhaPP npp : listNPP) {
                cbmMaNPP.addElement(npp.getMaNPP());
                cbmTenNPP.addElement(npp.getTenNPP());
            }
        }
        dsNPP = listNPP;
    }
}
