/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.IDAO;
import model.entity.KhachHang;
import model.dao.KhachHangDAO;

/**
 *
 * @author hoang minh duong
 */
public class QLKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form QLKhachHang
     */
    DefaultTableModel dtm;
    KhachHangDAO khachHangDAO;
    KhachHang tam;
    DefaultComboBoxModel cbmTimKiem;

    public QLKhachHang() {
        tam = new KhachHang();
        dtm = new DefaultTableModel();
        khachHangDAO = new KhachHangDAO();
        cbmTimKiem = new DefaultComboBoxModel();
        initComponents();
        cbTimKiem.setModel(cbmTimKiem);
        cbmTimKiem.removeAllElements();
        cbmTimKiem.addElement("Tim theo ma");
        cbmTimKiem.addElement("Tim theo ten");
        jTable1.setModel(dtm);
        dtm.addColumn("Mã");
        dtm.addColumn("Họ tên");
        dtm.addColumn("Số ĐT");
        dtm.addColumn("Địa chỉ");
        dtm.addColumn("Công nợ");
        tfCongNo.setEnabled(false);
        hienThiDs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTen = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lCongNo = new javax.swing.JLabel();
        tfCongNo = new javax.swing.JTextField();
        bTimKiem = new javax.swing.JButton();
        tfTimKiem = new javax.swing.JTextField();
        bKhoiPhuc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbTimKiem = new javax.swing.JComboBox<>();

        btThem.setText("ThêmKH");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("SửaKH");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("XóaKH");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        jLabel6.setText("Họ tên:");

        jLabel7.setText("Số ĐT:");

        jLabel8.setText("Địa chỉ:");

        tfTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ Tên", "Số điện thoại", "Địa Chỉ", "Công Nợ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lCongNo.setText("Công Nợ:");

        tfCongNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCongNoActionPerformed(evt);
            }
        });

        bTimKiem.setText("Tìm Kiếm");
        bTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTimKiemActionPerformed(evt);
            }
        });

        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });

        bKhoiPhuc.setText("Khôi phục");
        bKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKhoiPhucActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        cbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(bTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbTimKiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bKhoiPhuc))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btThem)
                                .addGap(18, 18, 18)
                                .addComponent(btSua))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lCongNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCongNo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btXoa)
                                .addGap(30, 30, 30)
                                .addComponent(btReset)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTimKiem)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bKhoiPhuc)
                    .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCongNo)
                            .addComponent(tfCongNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThem)
                            .addComponent(btSua))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btXoa)
                            .addComponent(btReset)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        tfCongNo.setText("0");
        tfCongNo.setEnabled(false);
        themKH();
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed

        // TODO add your handling code here:
        suaKH();
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        xoaKH();
    }//GEN-LAST:event_btXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int dong = jTable1.getSelectedRow();
        tam = khachHangDAO.hienDongClick(dong + 1);
        tfTen.setText(tam.getTenKH());
        tfSDT.setText(tam.getSoDT());
        tfDiaChi.setText(tam.getDiaChi());
        tfCongNo.setEnabled(true);
        tfCongNo.setText(tam.getCongNo() + "");
    }//GEN-LAST:event_jTable1MouseClicked

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        xoaText();

    }//GEN-LAST:event_btResetActionPerformed

    private void xoaText() {
        tfTimKiem.setText("");
        tfTen.setText("");
        tfSDT.setText("");
        tfDiaChi.setText("");
        tfCongNo.setText("0");
        tfCongNo.setEnabled(false);
    }
    private void bTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTimKiemActionPerformed
        // TODO add your handling code here:
        timKien();
    }//GEN-LAST:event_bTimKiemActionPerformed

    private void bKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKhoiPhucActionPerformed
        // TODO add your handling code here:
        hienThiDs();
    }//GEN-LAST:event_bKhoiPhucActionPerformed

    private void tfCongNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCongNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCongNoActionPerformed

    private void tfTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenActionPerformed

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKhoiPhuc;
    private javax.swing.JButton bTimKiem;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lCongNo;
    private javax.swing.JTextField tfCongNo;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables

    private void themKH() {
        if(!kiemTraText()){
            return;
        }
        String ten = tfTen.getText();
        String sdt = tfSDT.getText();
        String diaChi = tfDiaChi.getText();
        KhachHang kh = new KhachHang(ten, sdt, diaChi);
        KhachHang ok = khachHangDAO.themMoi(kh);
        if (ok != null) {
            JOptionPane.showMessageDialog(null, "Thêm mới thành công");
            xoaText();
        } else {
            JOptionPane.showMessageDialog(null, "Thêm mới thất bại");
            return;
        }
        hienThiDs();
    }
    private boolean kiemTraLaSo(String s){
        for (int i = 0; i < s.length(); i++) {
            if('0'>s.charAt(i) || s.charAt(i)>'9')
            {
                return false;
            }
        }
        return true;
    }
    private boolean kiemTraCongNo(String s){
         for (int i = 0; i < s.length(); i++) {
            if(s.charAt(i)!='.'&&'0'>s.charAt(i) || s.charAt(i)>'9')
            {
                return false;
            }
        }
        return true;
    }
    private boolean kiemTraText(){
        String hoTen = tfTen.getText().trim();
        String sdt = tfSDT.getText().trim();
        String diaChi = tfDiaChi.getText().trim();
        String congNo = tfCongNo.getText().trim();
        if(hoTen==""||sdt==""||diaChi==""||congNo==""){
            JOptionPane.showMessageDialog(null, "phai nhap day du du lieu");
            return false;
        }
        if(!kiemTraLaSo(sdt)||sdt.length()>15||sdt.length()<8){
            JOptionPane.showMessageDialog(null, "so dien thoai khong hop le");
            return false;
        }
        if(!kiemTraLaSo(congNo)){
            JOptionPane.showMessageDialog(null, "cong no khong hop le");
            return false;
        }
            return true;
    }
    private void hienThiDs() {
        tfCongNo.setText("0");
        List<KhachHang> list = khachHangDAO.getAll();
        if (dtm != null) {
            dtm.setRowCount(0);
            for (KhachHang kh : list) {
                dtm.addRow(new String[]{kh.getMaKH() + "", kh.getTenKH(), kh.getSoDT(), kh.getDiaChi(), kh.getCongNo() + ""});
            }
        }
    }

    private void suaKH() {
        if(!kiemTraText()){
            return;
        }
        tfCongNo.setEnabled(false);
        int ma = tam.getMaKH();
        String ten = tfTen.getText();
        String sdt = tfSDT.getText();
        String diaChi = tfDiaChi.getText();
        float congNo = Float.parseFloat(tfCongNo.getText());
        KhachHang kh = new KhachHang(ma, ten, sdt, diaChi, congNo);
        KhachHang kt = khachHangDAO.capNhat(kh);

        if (kt != null) {
            JOptionPane.showMessageDialog(null, "Sua thanh cong");
            xoaText();
        } else {
            JOptionPane.showMessageDialog(null, "Sua that bai");
            return;
        }
        tfCongNo.setEnabled(false);
        hienThiDs();
    }

    private void xoaKH() {
        tfCongNo.setEnabled(false);
        boolean ok = khachHangDAO.xoa(tam);
        if (ok) {
            JOptionPane.showMessageDialog(null, "xoa thanh cong");
            xoaText();
        } else {
            JOptionPane.showMessageDialog(null, "xoa that bai");
            return;
        }
        hienThiDs();
    }

    private void timKien() {
        String tuKhoa = tfTimKiem.getText().trim();
        int vt = cbTimKiem.getSelectedIndex();
        if (vt == 1) {
            List<KhachHang> list = khachHangDAO.timTheoTen(tuKhoa);
            if (list != null && !list.isEmpty()) {
                dtm.setRowCount(0);
                for (KhachHang kh : list) {
                    dtm.addRow(new String[]{kh.getMaKH() + "", kh.getTenKH(), kh.getSoDT(), kh.getDiaChi(), kh.getCongNo() + ""});
                }
            }
        }else{
            int ma;
            try{
                ma = Integer.parseInt(tuKhoa);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Ma khong hop le");
                return;
            }
            KhachHang kh = khachHangDAO.timTheoMa(ma);
            if(kh!=null){
                dtm.setRowCount(0);
                dtm.addRow(new String[]{kh.getMaKH()+"",kh.getTenKH(),kh.getSoDT(),kh.getDiaChi()});
            }
        }
    }

}
