/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.entity.KhachHang;
import model.dao.KhachHangDAO;
import model.entity.SanPham;
import model.dao.SanPhamDAO;

/**
 *
 * @author hoang minh duong
 */
public class QLSanPham extends javax.swing.JPanel {

    /**
     * Creates new form QLSanPham
     */
    DefaultTableModel dtm;
    SanPham tam;
    private SanPhamDAO sanPhamDao;

    public QLSanPham() {
        sanPhamDao = new SanPhamDAO();
        dtm = new DefaultTableModel();
        initComponents();
        tbSanPham.setModel(dtm);
        dtm.addColumn("Mã sản phẩm");
        dtm.addColumn("Tên sản phẩm");
        dtm.addColumn("Số lượng có");
        dtm.addColumn("Đơn vị tính");
        hienThiDS();
        lsoluongco.setVisible(false);
        txtsoluongco.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txttensp = new javax.swing.JTextField();
        lsoluongco = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsoluongco = new javax.swing.JTextField();
        txtdonvitinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnKhoiPhuc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Tên sp:");

        lsoluongco.setText("Số lượng có:");

        jLabel3.setText("Đơn vị tính:");

        txtsoluongco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongcoActionPerformed(evt);
            }
        });

        txtdonvitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdonvitinhActionPerformed(evt);
            }
        });

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng có", "Đơn vị tính"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);

        btnThem.setText("Thêm SP");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa SP");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa SP");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXoa)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSua))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(lsoluongco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsoluongco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(btnTimKiem)
                                .addGap(18, 18, 18)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnKhoiPhuc))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoiPhuc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtdonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lsoluongco)
                            .addComponent(txtsoluongco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua))
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
        int dong = tbSanPham.getSelectedRow();
        tam = sanPhamDao.hienDongClick(dong + 1);
        txttensp.setText(tam.getTenSP());
        lsoluongco.setVisible(true);
        txtsoluongco.setVisible(true);
        txtsoluongco.setText(tam.getSoLuongCo() + "");
        txtdonvitinh.setText(tam.getDonViTinh());
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        lsoluongco.setVisible(false);
        txtsoluongco.setVisible(false);
        String tenSP = txttensp.getText();
        String donViTinh = txtdonvitinh.getText();
        SanPham sp = new SanPham(tenSP, donViTinh);
        SanPham ok = sanPhamDao.themMoi(sp);
        if(ok!=null){
            JOptionPane.showMessageDialog(null, "them san pham thanh cong");
        }else {
            JOptionPane.showMessageDialog(null, "Thêm mới thất bại");
            return;
        }
        xoaTextFile();
        hienThiDS();
        
        
    }//GEN-LAST:event_btnThemActionPerformed
    private void xoaTextFile(){
        txttensp.setText("");
        txtdonvitinh.setText("");
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        lsoluongco.setVisible(false);
        txtsoluongco.setVisible(false);
        int ma = tam.getMaSP();
        String ten = txttensp.getText().trim();
        int soLuongCo = Integer.parseInt(txtsoluongco.getText());
        String donViTinh = txtdonvitinh.getText().trim();
        SanPham sp = new SanPham(ma, ten, soLuongCo, donViTinh);
        SanPham ok = sanPhamDao.capNhat(sp);
        if(ok!=null){
            JOptionPane.showMessageDialog(null, "cap nhat san pham thanh cong");
        }else{
            JOptionPane.showMessageDialog(null, "cap nhat san pham that bai");
            return;
        }
        xoaTextFile();
        hienThiDS();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        lsoluongco.setVisible(false);
        txtsoluongco.setVisible(false);
        boolean ok = sanPhamDao.xoa(tam);
        if(ok){
            JOptionPane.showMessageDialog(null, "cap nhat san pham thanh cong");
        }else{
            JOptionPane.showMessageDialog(null, "cap nhat san pham that bai");
            return;
        }
        xoaTextFile();
        hienThiDS();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String timKiem = txtTimKiem.getText().trim();
        List<SanPham> kq = sanPhamDao.timTheoTen(timKiem);
        if(kq!=null){
            dtm.setRowCount(0);
            for (SanPham sp : kq) {
                dtm.addRow(new String[]{sp.getMaSP()+"",sp.getTenSP(),sp.getSoLuongCo()+"",sp.getDonViTinh()});
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        hienThiDS();
    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void txtsoluongcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongcoActionPerformed

    private void txtdonvitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdonvitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdonvitinhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lsoluongco;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtdonvitinh;
    private javax.swing.JTextField txtsoluongco;
    private javax.swing.JTextField txttensp;
    // End of variables declaration//GEN-END:variables

    private void hienThiDS() {
        List<SanPham> all = sanPhamDao.getAll();
        if (dtm != null) {
            dtm.setRowCount(0);
            for (SanPham sp : all) {
                dtm.addRow(new String[]{sp.getMaSP() + "", sp.getTenSP(), sp.getSoLuongCo() + "", sp.getDonViTinh()});
            }
        }
    }
}
