/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khachhang;

import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import khachhang.IDAO;
import khachhang.KhachHang;
import khachhang.KhachHangDAO;

/**
 *
 * @author hoang minh duong
 */
public class QLKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form QLKhachHang
     */
	
    DefaultTableModel dtm;
    KhachHangDAO khachHangDAO;
    KhachHang tam;
    public QLKhachHang() {
        tam = new KhachHang();
        dtm = new DefaultTableModel();
        khachHangDAO = new KhachHangDAO();
        initComponents();
        jTable1.setModel(dtm);
        dtm.addColumn("MÃ£");
        dtm.addColumn("Há»� tÃªn");
        dtm.addColumn("Sá»‘ Ä�T");
        dtm.addColumn("Ä�á»‹a chá»‰");
        dtm.addColumn("CÃ´ng ná»£");
        hienThiDs();
        lCongNo.setVisible(false);
        tfCongNo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTen = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lCongNo = new javax.swing.JLabel();
        tfCongNo = new javax.swing.JTextField();
        bTimKiem = new javax.swing.JButton();
        tfTimKiem = new javax.swing.JTextField();
        bKhoiPhuc = new javax.swing.JButton();

        btThem.setText("ThÃªmKH");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("Sá»­aKH");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("XÃ³aKH");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        jLabel6.setText("Há»� tÃªn:");

        jLabel7.setText("Sá»‘ Ä�T:");

        jLabel8.setText("Ä�á»‹a chá»‰:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ£", "Há»� TÃªn", "Sá»‘ Ä‘iá»‡n thoáº¡i", "Ä�á»‹a Chá»‰", "CÃ´ng Ná»£"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lCongNo.setText("CÃ´ng Ná»£:");

        bTimKiem.setText("TÃ¬m Kiáº¿m");
        bTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTimKiemActionPerformed(evt);
            }
        });

        bKhoiPhuc.setText("KhÃ´i phá»¥c");
        bKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKhoiPhucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btXoa)
                        .addGap(30, 30, 30)
                        .addComponent(btReset))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btThem)
                        .addGap(18, 18, 18)
                        .addComponent(btSua))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCongNo)
                                .addGap(18, 18, 18)
                                .addComponent(tfCongNo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(bTimKiem)
                .addGap(27, 27, 27)
                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(bKhoiPhuc)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCongNo)
                            .addComponent(tfCongNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThem)
                            .addComponent(btSua))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btXoa)
                            .addComponent(btReset)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTimKiem)
                            .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bKhoiPhuc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        tfCongNo.setText("0");
        themKH();
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed

        // TODO add your handling code here:
        suaKH();
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
               // TODO add your handling code here:
        xoaKH();
    }//GEN-LAST:event_btXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int dong = jTable1.getSelectedRow();
        tam = khachHangDAO.hienDongClick(dong+1);
        tfTen.setText(tam.getTen());
        tfSDT.setText(tam.getSoDT());
        tfDiaChi.setText(tam.getDiaChi());
        lCongNo.setVisible(true);
        tfCongNo.setVisible(true);
        tfCongNo.setText(tam.getCongNo()+"");
    }//GEN-LAST:event_jTable1MouseClicked

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        tfTen.setText("");
        tfSDT.setText("");
        tfDiaChi.setText("");
        tfCongNo.setVisible(false);
        lCongNo.setVisible(false);
        
    }//GEN-LAST:event_btResetActionPerformed

    private void bTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTimKiemActionPerformed
        // TODO add your handling code here:
        timKien();
    }//GEN-LAST:event_bTimKiemActionPerformed

    private void bKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKhoiPhucActionPerformed
        // TODO add your handling code here:
        hienThiDs();
    }//GEN-LAST:event_bKhoiPhucActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKhoiPhuc;
    private javax.swing.JButton bTimKiem;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lCongNo;
    private javax.swing.JTextField tfCongNo;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables

    private void themKH() {
        tfCongNo.setVisible(false);
        lCongNo.setVisible(false);
        String ten = tfTen.getText();
        String sdt = tfSDT.getText();
        String diaChi = tfDiaChi.getText();
        KhachHang kh = new KhachHang(ten, sdt, diaChi);
        KhachHang ok = khachHangDAO.themMoi(kh);
        if (ok != null) {
            JOptionPane.showMessageDialog(null, "ThÃªm má»›i thÃ nh cÃ´ng");
        } else {
            JOptionPane.showMessageDialog(null, "ThÃªm má»›i tháº¥t báº¡i");
            return;
        }
        hienThiDs();
    }

    private void hienThiDs() {
        List<KhachHang> list = khachHangDAO.getAll();
        if (dtm != null) {
            dtm.setRowCount(0);
            for (KhachHang kh : list) {
                dtm.addRow(new String[]{kh.getMa() + "", kh.getTen(), kh.getSoDT(), kh.getDiaChi(),kh.getCongNo()+""});
            }
        }
    }

    private void suaKH() {
        int ma = tam.getMa();
        String ten = tfTen.getText();
        String sdt = tfSDT.getText();
        String diaChi = tfDiaChi.getText();
        float congNo = Float.parseFloat(tfCongNo.getText());
        KhachHang kh = new KhachHang(ma, ten, sdt, diaChi, congNo);
        KhachHang kt = khachHangDAO.capNhat(kh);
        
        if (kt != null) {
            JOptionPane.showMessageDialog(null, "Sua thanh cong");

        } else {
            JOptionPane.showMessageDialog(null, "Sua that bai");
            return;
        }
        lCongNo.setVisible(false);
        tfCongNo.setVisible(false);
        hienThiDs();
    }

    private void xoaKH() {
        tfCongNo.setVisible(false);
        lCongNo.setVisible(false);
        boolean ok = khachHangDAO.xoa(tam);
        if(ok){
            JOptionPane.showMessageDialog(null, "xoa thanh cong");
        }else{
            JOptionPane.showMessageDialog(null, "xoa that bai");
            return;
        }
        hienThiDs();
    }

    private void timKien() {
        String tuKhoa = tfTimKiem.getText();
        List<KhachHang> list = khachHangDAO.timTheoTen(tuKhoa);
        if(list!=null&&!list.isEmpty()){
            dtm.setRowCount(0);
            for (KhachHang kh : list) {
                dtm.addRow(new String[]{kh.getMa()+"",kh.getTen(),kh.getSoDT(),kh.getDiaChi(),kh.getCongNo()+""});
            }
        }
    }
   
    
}
